# -*- coding: utf-8 -*-
"""HW Day 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/153llbnJ0y-iF30Ksca8TPUKWM90gN0gy
"""

class Animals:
  def __init__(self, name, age, gender):
    self.Name = name
    self.Age = age
    self.Gender = gender
  def printfeatures(self):
    print(self.Name + ' is ' + str(self.Age) + ' years old, ' + self.Gender)
class Cats(Animals):
  def __init__(self, name, age, gender):
    super().__init__(name, age, gender)
class Dogs(Animals):
  def __init__(self, name, age, gender):
    Animals.__init__(self, name, age, gender)
 
x = Cats('Patis', '2', 'Female')
y = Dogs('Cango', '13', 'Male')
  
x.printfeatures()
y.printfeatures()