# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QLCDhJbjaLJxaJRfRaVR8blXtQTZdOL2
"""

mylist = ['pink','purple','red','yellow','blue','green']
mylist[0:3] = ['yellow','blue','green']
mylist[3:6] = ['pink','purple','red']
print(mylist)

n = int(input('Please enter a one digit number:'))
nums = list(range(n))
even_nums = [i for i in nums if i % 2 == 0]
even_nums.append(n)
print(even_nums)

