# -*- coding: utf-8 -*-
"""HW Day 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AIyb2w6hQ2Lq3rnab5U3rkWS2uoqx_5z
"""

def prime(n):
   if (n == 0 or n == 1):
    return False
   elif (n == 2 ):
    return True
   else:
     for i in range(2,n):
      if (n % i == 0):
        return False
   return True
for n in range (0,101):
   if prime (n):
     print(n)